name: CI pipeline

on: [push]

env:
  build_dir: build
  cflags: -Werror -fsanitize=address
  lflags: -fsanitize=address

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure
        run: >
          cmake -B ${{env.build_dir}}
          -DCMAKE_C_FLAGS='${{env.cflags}}'
          -DCMAKE_EXE_LINKER_FLAGS='${{env.lflags}}'
      - name: Build
        run: cmake --build ${{env.build_dir}}
      - name: Test
        run: ${{env.build_dir}}/mylib-test
